development:
  adapter: postgresql
  encoding: unicode
  database: myyelp_dev
  pool: 5
  username: rachelminto
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: myyelp_test
  pool: 5
  username: rachelminto
  password: